import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/Header/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Andrew Fish Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* side  */}
        <Header />

        {/* main/center */}
        <div id="main-column">
          {/* page.tsx */}
          <div id="children">{children}</div>
          <footer>footer</footer>
        </div>
      </body>
    </html>
  );
}
